apiVersion: v1
kind: Service
metadata:
  name: laravel-product-two
  annotations:
    cloud.google.com/backend-config: '{"default": "laravel-product-two"}'
spec:
  type: ClusterIP
  selector:
    app: laravel-product-two
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80