apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-product-two
spec:
  selector:
    matchLabels:
      app: laravel-product-two
  template:
    metadata:
      labels:
        app: laravel-product-two
    spec:
      initContainers:
      - name: init-shared-data
        image: laravel-product-two
        envFrom:
        - secretRef:
            name: laravel-product-two-env
        volumeMounts:
        - name: laravel-product-two-shared-data
          mountPath: /shared-data
        command: ['cp', '-a', '/var/www/html/.', '/shared-data' ]
      containers:
      - name: laravel
        image: laravel-product-two
        resources:
          requests:
            cpu: 10m
            memory: 20M
          limits:
            cpu: 400m
            memory: 400M
        envFrom:
        - secretRef:
            name: laravel-product-two-env
      - name: nginx
        image: nginx:1.19.3-alpine
        resources:
          requests:
            cpu: 10m
            memory: 20M
          limits:
            cpu: 400m
            memory: 400M
        volumeMounts:
          - name: laravel-product-two-shared-data
            mountPath: /var/www/html
          - name: laravel-product-two-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
      - name: laravel-product-two-shared-data
        emptyDir: {}
      - name: laravel-product-two-config
        configMap:
          name: laravel-product-two-config